/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { PrismaService } from "../../prisma/prisma.service";
import { Prisma, OwnFirst } from "@prisma/client";

export class OwnFirstServiceBase {
  constructor(protected readonly prisma: PrismaService) {}

  async count<T extends Prisma.OwnFirstCountArgs>(
    args: Prisma.SelectSubset<T, Prisma.OwnFirstCountArgs>
  ): Promise<number> {
    return this.prisma.ownFirst.count(args);
  }

  async ownFirsts<T extends Prisma.OwnFirstFindManyArgs>(
    args: Prisma.SelectSubset<T, Prisma.OwnFirstFindManyArgs>
  ): Promise<OwnFirst[]> {
    return this.prisma.ownFirst.findMany(args);
  }
  async ownFirst<T extends Prisma.OwnFirstFindUniqueArgs>(
    args: Prisma.SelectSubset<T, Prisma.OwnFirstFindUniqueArgs>
  ): Promise<OwnFirst | null> {
    return this.prisma.ownFirst.findUnique(args);
  }
  async createOwnFirst<T extends Prisma.OwnFirstCreateArgs>(
    args: Prisma.SelectSubset<T, Prisma.OwnFirstCreateArgs>
  ): Promise<OwnFirst> {
    return this.prisma.ownFirst.create<T>(args);
  }
  async updateOwnFirst<T extends Prisma.OwnFirstUpdateArgs>(
    args: Prisma.SelectSubset<T, Prisma.OwnFirstUpdateArgs>
  ): Promise<OwnFirst> {
    return this.prisma.ownFirst.update<T>(args);
  }
  async deleteOwnFirst<T extends Prisma.OwnFirstDeleteArgs>(
    args: Prisma.SelectSubset<T, Prisma.OwnFirstDeleteArgs>
  ): Promise<OwnFirst> {
    return this.prisma.ownFirst.delete(args);
  }
}
